version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: eurobot_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: eurobot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - eurobot-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eurobot_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/eurobot?authSource=admin
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data:ro
    networks:
      - eurobot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eurobot_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - eurobot-network

volumes:
  mongodb_data:

networks:
  eurobot-network:
    driver: bridge
